version: '3.4'

services:
  calculator:
    image: calculator:dev
    container_name: Calculator
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Calculator"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_calculator$
    volumes:
      - D:\Programmering\Repositories\personal\Bowling\Bowling\Calculator:/app
      - D:\Programmering\Repositories\personal\Bowling\Bowling:/src
      - C:\Users\Malte\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_calculator$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_calculator$ \"/app/bin/Debug/netcoreapp3.1/Calculator.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  presenter:
    image: presenter:dev
    container_name: Presenter
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Presenter"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_presenter$
    volumes:
      - D:\Programmering\Repositories\personal\Bowling\Bowling\Presenter:/app
      - D:\Programmering\Repositories\personal\Bowling\Bowling:/src
      - C:\Users\Malte\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_presenter$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_presenter$ \"/app/bin/Debug/netcoreapp3.1/Presenter.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  rolls:
    image: rolls:dev
    container_name: Rolls
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Rolls"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rolls$
    volumes:
      - D:\Programmering\Repositories\personal\Bowling\Bowling\Rolls:/app
      - D:\Programmering\Repositories\personal\Bowling\Bowling:/src
      - C:\Users\Malte\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_rolls$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rolls$ \"/app/bin/Debug/netcoreapp3.1/Rolls.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
