//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClientWSU2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://webServiceTaskTwo.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServiceTaskTwo.com/", ConfigurationName="ServiceReference1.WebService2Soap")]
    public interface WebService2Soap {
        
        // CODEGEN: Generating message contract since element name GetAllMemberCoursesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMemberCourses", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponse GetAllMemberCourses(ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMemberCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponse> GetAllMemberCoursesAsync(ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMembersResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMembers", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetAllMembersResponse GetAllMembers(ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMembers", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllMembersResponse> GetAllMembersAsync(ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCoursesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllCourses", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponse GetAllCourses(ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponse> GetAllCoursesAsync(ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseColumnNamesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetCourseColumnNames", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponse GetCourseColumnNames(ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetCourseColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponse> GetCourseColumnNamesAsync(ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMemberColumnNamesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberColumnNames", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponse GetMemberColumnNames(ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponse> GetMemberColumnNamesAsync(ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMemberCourseColumnNamesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberCourseColumnNames", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponse GetMemberCourseColumnNames(ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberCourseColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponse> GetMemberCourseColumnNamesAsync(ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name table from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllColumns", ReplyAction="*")]
        ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponse GetAllColumns(ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponse> GetAllColumnsAsync(ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMemberCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMemberCourses", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequestBody Body;
        
        public GetAllMemberCoursesRequest() {
        }
        
        public GetAllMemberCoursesRequest(ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMemberCoursesRequestBody {
        
        public GetAllMemberCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMemberCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMemberCoursesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponseBody Body;
        
        public GetAllMemberCoursesResponse() {
        }
        
        public GetAllMemberCoursesResponse(ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllMemberCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllMemberCoursesResult;
        
        public GetAllMemberCoursesResponseBody() {
        }
        
        public GetAllMemberCoursesResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllMemberCoursesResult) {
            this.GetAllMemberCoursesResult = GetAllMemberCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMembers", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllMembersRequestBody Body;
        
        public GetAllMembersRequest() {
        }
        
        public GetAllMembersRequest(ConsoleClientWSU2.ServiceReference1.GetAllMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMembersRequestBody {
        
        public GetAllMembersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMembersResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllMembersResponseBody Body;
        
        public GetAllMembersResponse() {
        }
        
        public GetAllMembersResponse(ConsoleClientWSU2.ServiceReference1.GetAllMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllMembersResult;
        
        public GetAllMembersResponseBody() {
        }
        
        public GetAllMembersResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllMembersResult) {
            this.GetAllMembersResult = GetAllMembersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourses", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequestBody Body;
        
        public GetAllCoursesRequest() {
        }
        
        public GetAllCoursesRequest(ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCoursesRequestBody {
        
        public GetAllCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCoursesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponseBody Body;
        
        public GetAllCoursesResponse() {
        }
        
        public GetAllCoursesResponse(ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllCoursesResult;
        
        public GetAllCoursesResponseBody() {
        }
        
        public GetAllCoursesResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllCoursesResult) {
            this.GetAllCoursesResult = GetAllCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseColumnNames", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequestBody Body;
        
        public GetCourseColumnNamesRequest() {
        }
        
        public GetCourseColumnNamesRequest(ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCourseColumnNamesRequestBody {
        
        public GetCourseColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseColumnNamesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponseBody Body;
        
        public GetCourseColumnNamesResponse() {
        }
        
        public GetCourseColumnNamesResponse(ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetCourseColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetCourseColumnNamesResult;
        
        public GetCourseColumnNamesResponseBody() {
        }
        
        public GetCourseColumnNamesResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetCourseColumnNamesResult) {
            this.GetCourseColumnNamesResult = GetCourseColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberColumnNames", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequestBody Body;
        
        public GetMemberColumnNamesRequest() {
        }
        
        public GetMemberColumnNamesRequest(ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMemberColumnNamesRequestBody {
        
        public GetMemberColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberColumnNamesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponseBody Body;
        
        public GetMemberColumnNamesResponse() {
        }
        
        public GetMemberColumnNamesResponse(ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetMemberColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetMemberColumnNamesResult;
        
        public GetMemberColumnNamesResponseBody() {
        }
        
        public GetMemberColumnNamesResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetMemberColumnNamesResult) {
            this.GetMemberColumnNamesResult = GetMemberColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberCourseColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberCourseColumnNames", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequestBody Body;
        
        public GetMemberCourseColumnNamesRequest() {
        }
        
        public GetMemberCourseColumnNamesRequest(ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMemberCourseColumnNamesRequestBody {
        
        public GetMemberCourseColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberCourseColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberCourseColumnNamesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponseBody Body;
        
        public GetMemberCourseColumnNamesResponse() {
        }
        
        public GetMemberCourseColumnNamesResponse(ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetMemberCourseColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetMemberCourseColumnNamesResult;
        
        public GetMemberCourseColumnNamesResponseBody() {
        }
        
        public GetMemberCourseColumnNamesResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetMemberCourseColumnNamesResult) {
            this.GetMemberCourseColumnNamesResult = GetMemberCourseColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumns", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequestBody Body;
        
        public GetAllColumnsRequest() {
        }
        
        public GetAllColumnsRequest(ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllColumnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string table;
        
        public GetAllColumnsRequestBody() {
        }
        
        public GetAllColumnsRequestBody(string table) {
            this.table = table;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponseBody Body;
        
        public GetAllColumnsResponse() {
        }
        
        public GetAllColumnsResponse(ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString GetAllColumnsResult;
        
        public GetAllColumnsResponseBody() {
        }
        
        public GetAllColumnsResponseBody(ConsoleClientWSU2.ServiceReference1.ArrayOfString GetAllColumnsResult) {
            this.GetAllColumnsResult = GetAllColumnsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : ConsoleClientWSU2.ServiceReference1.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<ConsoleClientWSU2.ServiceReference1.WebService2Soap>, ConsoleClientWSU2.ServiceReference1.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllMemberCourses(ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest request) {
            return base.Channel.GetAllMemberCourses(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllMemberCourses() {
            ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequestBody();
            ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllMemberCourses(inValue);
            return retVal.Body.GetAllMemberCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllMemberCoursesAsync(ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest request) {
            return base.Channel.GetAllMemberCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesResponse> GetAllMemberCoursesAsync() {
            ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllMemberCoursesRequestBody();
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllMemberCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetAllMembersResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllMembers(ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest request) {
            return base.Channel.GetAllMembers(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllMembers() {
            ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllMembersRequestBody();
            ConsoleClientWSU2.ServiceReference1.GetAllMembersResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllMembers(inValue);
            return retVal.Body.GetAllMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllMembersResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllMembersAsync(ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest request) {
            return base.Channel.GetAllMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllMembersResponse> GetAllMembersAsync() {
            ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllMembersRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllMembersRequestBody();
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllMembersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllCourses(ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest request) {
            return base.Channel.GetAllCourses(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetAllCourses() {
            ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequestBody();
            ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllCourses(inValue);
            return retVal.Body.GetAllCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllCoursesAsync(ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest request) {
            return base.Channel.GetAllCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllCoursesResponse> GetAllCoursesAsync() {
            ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllCoursesRequestBody();
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetCourseColumnNames(ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest request) {
            return base.Channel.GetCourseColumnNames(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetCourseColumnNames() {
            ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequestBody();
            ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetCourseColumnNames(inValue);
            return retVal.Body.GetCourseColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetCourseColumnNamesAsync(ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest request) {
            return base.Channel.GetCourseColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesResponse> GetCourseColumnNamesAsync() {
            ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetCourseColumnNamesRequestBody();
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetCourseColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetMemberColumnNames(ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest request) {
            return base.Channel.GetMemberColumnNames(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetMemberColumnNames() {
            ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequestBody();
            ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetMemberColumnNames(inValue);
            return retVal.Body.GetMemberColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetMemberColumnNamesAsync(ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest request) {
            return base.Channel.GetMemberColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesResponse> GetMemberColumnNamesAsync() {
            ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetMemberColumnNamesRequestBody();
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetMemberColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetMemberCourseColumnNames(ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest request) {
            return base.Channel.GetMemberCourseColumnNames(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString[] GetMemberCourseColumnNames() {
            ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequestBody();
            ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetMemberCourseColumnNames(inValue);
            return retVal.Body.GetMemberCourseColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetMemberCourseColumnNamesAsync(ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest request) {
            return base.Channel.GetMemberCourseColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesResponse> GetMemberCourseColumnNamesAsync() {
            ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetMemberCourseColumnNamesRequestBody();
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetMemberCourseColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponse ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllColumns(ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest request) {
            return base.Channel.GetAllColumns(request);
        }
        
        public ConsoleClientWSU2.ServiceReference1.ArrayOfString GetAllColumns(string table) {
            ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequestBody();
            inValue.Body.table = table;
            ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponse retVal = ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllColumns(inValue);
            return retVal.Body.GetAllColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponse> ConsoleClientWSU2.ServiceReference1.WebService2Soap.GetAllColumnsAsync(ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest request) {
            return base.Channel.GetAllColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientWSU2.ServiceReference1.GetAllColumnsResponse> GetAllColumnsAsync(string table) {
            ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest inValue = new ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequest();
            inValue.Body = new ConsoleClientWSU2.ServiceReference1.GetAllColumnsRequestBody();
            inValue.Body.table = table;
            return ((ConsoleClientWSU2.ServiceReference1.WebService2Soap)(this)).GetAllColumnsAsync(inValue);
        }
    }
}
