//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://stableGeniuses.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stableGeniuses.com/", ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name file from namespace http://stableGeniuses.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stableGeniuses.com/GetFileContents", ReplyAction="*")]
        WpfApp2.ServiceReference2.GetFileContentsResponse GetFileContents(WpfApp2.ServiceReference2.GetFileContentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stableGeniuses.com/GetFileContents", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp2.ServiceReference2.GetFileContentsResponse> GetFileContentsAsync(WpfApp2.ServiceReference2.GetFileContentsRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://stableGeniuses.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stableGeniuses.com/HelloWorld", ReplyAction="*")]
        WpfApp2.ServiceReference2.HelloWorldResponse HelloWorld(WpfApp2.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stableGeniuses.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp2.ServiceReference2.HelloWorldResponse> HelloWorldAsync(WpfApp2.ServiceReference2.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContents", Namespace="http://stableGeniuses.com/", Order=0)]
        public WpfApp2.ServiceReference2.GetFileContentsRequestBody Body;
        
        public GetFileContentsRequest() {
        }
        
        public GetFileContentsRequest(WpfApp2.ServiceReference2.GetFileContentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stableGeniuses.com/")]
    public partial class GetFileContentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file;
        
        public GetFileContentsRequestBody() {
        }
        
        public GetFileContentsRequestBody(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContentsResponse", Namespace="http://stableGeniuses.com/", Order=0)]
        public WpfApp2.ServiceReference2.GetFileContentsResponseBody Body;
        
        public GetFileContentsResponse() {
        }
        
        public GetFileContentsResponse(WpfApp2.ServiceReference2.GetFileContentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stableGeniuses.com/")]
    public partial class GetFileContentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp2.ServiceReference2.ArrayOfString GetFileContentsResult;
        
        public GetFileContentsResponseBody() {
        }
        
        public GetFileContentsResponseBody(WpfApp2.ServiceReference2.ArrayOfString GetFileContentsResult) {
            this.GetFileContentsResult = GetFileContentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://stableGeniuses.com/", Order=0)]
        public WpfApp2.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WpfApp2.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://stableGeniuses.com/", Order=0)]
        public WpfApp2.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WpfApp2.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stableGeniuses.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WpfApp2.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WpfApp2.ServiceReference2.WebService1Soap>, WpfApp2.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.ServiceReference2.GetFileContentsResponse WpfApp2.ServiceReference2.WebService1Soap.GetFileContents(WpfApp2.ServiceReference2.GetFileContentsRequest request) {
            return base.Channel.GetFileContents(request);
        }
        
        public WpfApp2.ServiceReference2.ArrayOfString GetFileContents(string file) {
            WpfApp2.ServiceReference2.GetFileContentsRequest inValue = new WpfApp2.ServiceReference2.GetFileContentsRequest();
            inValue.Body = new WpfApp2.ServiceReference2.GetFileContentsRequestBody();
            inValue.Body.file = file;
            WpfApp2.ServiceReference2.GetFileContentsResponse retVal = ((WpfApp2.ServiceReference2.WebService1Soap)(this)).GetFileContents(inValue);
            return retVal.Body.GetFileContentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp2.ServiceReference2.GetFileContentsResponse> WpfApp2.ServiceReference2.WebService1Soap.GetFileContentsAsync(WpfApp2.ServiceReference2.GetFileContentsRequest request) {
            return base.Channel.GetFileContentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp2.ServiceReference2.GetFileContentsResponse> GetFileContentsAsync(string file) {
            WpfApp2.ServiceReference2.GetFileContentsRequest inValue = new WpfApp2.ServiceReference2.GetFileContentsRequest();
            inValue.Body = new WpfApp2.ServiceReference2.GetFileContentsRequestBody();
            inValue.Body.file = file;
            return ((WpfApp2.ServiceReference2.WebService1Soap)(this)).GetFileContentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.ServiceReference2.HelloWorldResponse WpfApp2.ServiceReference2.WebService1Soap.HelloWorld(WpfApp2.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WpfApp2.ServiceReference2.HelloWorldRequest inValue = new WpfApp2.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WpfApp2.ServiceReference2.HelloWorldRequestBody();
            WpfApp2.ServiceReference2.HelloWorldResponse retVal = ((WpfApp2.ServiceReference2.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp2.ServiceReference2.HelloWorldResponse> WpfApp2.ServiceReference2.WebService1Soap.HelloWorldAsync(WpfApp2.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp2.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            WpfApp2.ServiceReference2.HelloWorldRequest inValue = new WpfApp2.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WpfApp2.ServiceReference2.HelloWorldRequestBody();
            return ((WpfApp2.ServiceReference2.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}
