//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClientWSU2.ServiceReferenceWSU2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://webServiceTaskTwo.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServiceTaskTwo.com/", ConfigurationName="ServiceReferenceWSU2.WebService2Soap")]
    public interface WebService2Soap {
        
        // CODEGEN: Generating message contract since element name GetAllMemberCoursesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMemberCourses", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponse GetAllMemberCourses(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMemberCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponse> GetAllMemberCoursesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMembersResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMembers", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponse GetAllMembers(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllMembers", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponse> GetAllMembersAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCoursesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllCourses", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponse GetAllCourses(WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponse> GetAllCoursesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseColumnNamesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetCourseColumnNames", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponse GetCourseColumnNames(WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetCourseColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponse> GetCourseColumnNamesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMemberColumnNamesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberColumnNames", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponse GetMemberColumnNames(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponse> GetMemberColumnNamesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMemberCourseColumnNamesResult from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberCourseColumnNames", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponse GetMemberCourseColumnNames(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetMemberCourseColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponse> GetMemberCourseColumnNamesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name table from namespace http://webServiceTaskTwo.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllColumns", ReplyAction="*")]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponse GetAllColumns(WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceTaskTwo.com/GetAllColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponse> GetAllColumnsAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMemberCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMemberCourses", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequestBody Body;
        
        public GetAllMemberCoursesRequest() {
        }
        
        public GetAllMemberCoursesRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMemberCoursesRequestBody {
        
        public GetAllMemberCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMemberCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMemberCoursesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponseBody Body;
        
        public GetAllMemberCoursesResponse() {
        }
        
        public GetAllMemberCoursesResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllMemberCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllMemberCoursesResult;
        
        public GetAllMemberCoursesResponseBody() {
        }
        
        public GetAllMemberCoursesResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllMemberCoursesResult) {
            this.GetAllMemberCoursesResult = GetAllMemberCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMembers", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequestBody Body;
        
        public GetAllMembersRequest() {
        }
        
        public GetAllMembersRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMembersRequestBody {
        
        public GetAllMembersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMembersResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponseBody Body;
        
        public GetAllMembersResponse() {
        }
        
        public GetAllMembersResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllMembersResult;
        
        public GetAllMembersResponseBody() {
        }
        
        public GetAllMembersResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllMembersResult) {
            this.GetAllMembersResult = GetAllMembersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourses", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequestBody Body;
        
        public GetAllCoursesRequest() {
        }
        
        public GetAllCoursesRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCoursesRequestBody {
        
        public GetAllCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCoursesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponseBody Body;
        
        public GetAllCoursesResponse() {
        }
        
        public GetAllCoursesResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllCoursesResult;
        
        public GetAllCoursesResponseBody() {
        }
        
        public GetAllCoursesResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllCoursesResult) {
            this.GetAllCoursesResult = GetAllCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseColumnNames", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequestBody Body;
        
        public GetCourseColumnNamesRequest() {
        }
        
        public GetCourseColumnNamesRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCourseColumnNamesRequestBody {
        
        public GetCourseColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseColumnNamesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponseBody Body;
        
        public GetCourseColumnNamesResponse() {
        }
        
        public GetCourseColumnNamesResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetCourseColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetCourseColumnNamesResult;
        
        public GetCourseColumnNamesResponseBody() {
        }
        
        public GetCourseColumnNamesResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetCourseColumnNamesResult) {
            this.GetCourseColumnNamesResult = GetCourseColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberColumnNames", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequestBody Body;
        
        public GetMemberColumnNamesRequest() {
        }
        
        public GetMemberColumnNamesRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMemberColumnNamesRequestBody {
        
        public GetMemberColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberColumnNamesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponseBody Body;
        
        public GetMemberColumnNamesResponse() {
        }
        
        public GetMemberColumnNamesResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetMemberColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetMemberColumnNamesResult;
        
        public GetMemberColumnNamesResponseBody() {
        }
        
        public GetMemberColumnNamesResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetMemberColumnNamesResult) {
            this.GetMemberColumnNamesResult = GetMemberColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberCourseColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberCourseColumnNames", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequestBody Body;
        
        public GetMemberCourseColumnNamesRequest() {
        }
        
        public GetMemberCourseColumnNamesRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMemberCourseColumnNamesRequestBody {
        
        public GetMemberCourseColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberCourseColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberCourseColumnNamesResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponseBody Body;
        
        public GetMemberCourseColumnNamesResponse() {
        }
        
        public GetMemberCourseColumnNamesResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetMemberCourseColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetMemberCourseColumnNamesResult;
        
        public GetMemberCourseColumnNamesResponseBody() {
        }
        
        public GetMemberCourseColumnNamesResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetMemberCourseColumnNamesResult) {
            this.GetMemberCourseColumnNamesResult = GetMemberCourseColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumns", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequestBody Body;
        
        public GetAllColumnsRequest() {
        }
        
        public GetAllColumnsRequest(WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllColumnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string table;
        
        public GetAllColumnsRequestBody() {
        }
        
        public GetAllColumnsRequestBody(string table) {
            this.table = table;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsResponse", Namespace="http://webServiceTaskTwo.com/", Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponseBody Body;
        
        public GetAllColumnsResponse() {
        }
        
        public GetAllColumnsResponse(WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceTaskTwo.com/")]
    public partial class GetAllColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString GetAllColumnsResult;
        
        public GetAllColumnsResponseBody() {
        }
        
        public GetAllColumnsResponseBody(WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString GetAllColumnsResult) {
            this.GetAllColumnsResult = GetAllColumnsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap>, WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllMemberCourses(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest request) {
            return base.Channel.GetAllMemberCourses(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllMemberCourses() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequestBody();
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllMemberCourses(inValue);
            return retVal.Body.GetAllMemberCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllMemberCoursesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest request) {
            return base.Channel.GetAllMemberCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesResponse> GetAllMemberCoursesAsync() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMemberCoursesRequestBody();
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllMemberCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllMembers(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest request) {
            return base.Channel.GetAllMembers(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllMembers() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequestBody();
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllMembers(inValue);
            return retVal.Body.GetAllMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllMembersAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest request) {
            return base.Channel.GetAllMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersResponse> GetAllMembersAsync() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllMembersRequestBody();
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllMembersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllCourses(WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest request) {
            return base.Channel.GetAllCourses(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetAllCourses() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequestBody();
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllCourses(inValue);
            return retVal.Body.GetAllCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllCoursesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest request) {
            return base.Channel.GetAllCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesResponse> GetAllCoursesAsync() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllCoursesRequestBody();
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetCourseColumnNames(WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest request) {
            return base.Channel.GetCourseColumnNames(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetCourseColumnNames() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequestBody();
            WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetCourseColumnNames(inValue);
            return retVal.Body.GetCourseColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetCourseColumnNamesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest request) {
            return base.Channel.GetCourseColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesResponse> GetCourseColumnNamesAsync() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetCourseColumnNamesRequestBody();
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetCourseColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetMemberColumnNames(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest request) {
            return base.Channel.GetMemberColumnNames(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetMemberColumnNames() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequestBody();
            WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetMemberColumnNames(inValue);
            return retVal.Body.GetMemberColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetMemberColumnNamesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest request) {
            return base.Channel.GetMemberColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesResponse> GetMemberColumnNamesAsync() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberColumnNamesRequestBody();
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetMemberColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetMemberCourseColumnNames(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest request) {
            return base.Channel.GetMemberCourseColumnNames(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString[] GetMemberCourseColumnNames() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequestBody();
            WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetMemberCourseColumnNames(inValue);
            return retVal.Body.GetMemberCourseColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetMemberCourseColumnNamesAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest request) {
            return base.Channel.GetMemberCourseColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesResponse> GetMemberCourseColumnNamesAsync() {
            WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetMemberCourseColumnNamesRequestBody();
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetMemberCourseColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponse WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllColumns(WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest request) {
            return base.Channel.GetAllColumns(request);
        }
        
        public WindowsClientWSU2.ServiceReferenceWSU2.ArrayOfString GetAllColumns(string table) {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequestBody();
            inValue.Body.table = table;
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponse retVal = ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllColumns(inValue);
            return retVal.Body.GetAllColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponse> WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap.GetAllColumnsAsync(WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest request) {
            return base.Channel.GetAllColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsResponse> GetAllColumnsAsync(string table) {
            WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest inValue = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequest();
            inValue.Body = new WindowsClientWSU2.ServiceReferenceWSU2.GetAllColumnsRequestBody();
            inValue.Body.table = table;
            return ((WindowsClientWSU2.ServiceReferenceWSU2.WebService2Soap)(this)).GetAllColumnsAsync(inValue);
        }
    }
}
