//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWebServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://stableGeniuses.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stableGeniuses.com/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name file from namespace http://stableGeniuses.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stableGeniuses.com/GetFileContents", ReplyAction="*")]
        WpfWebServiceClient.ServiceReference1.GetFileContentsResponse GetFileContents(WpfWebServiceClient.ServiceReference1.GetFileContentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stableGeniuses.com/GetFileContents", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfWebServiceClient.ServiceReference1.GetFileContentsResponse> GetFileContentsAsync(WpfWebServiceClient.ServiceReference1.GetFileContentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContents", Namespace="http://stableGeniuses.com/", Order=0)]
        public WpfWebServiceClient.ServiceReference1.GetFileContentsRequestBody Body;
        
        public GetFileContentsRequest() {
        }
        
        public GetFileContentsRequest(WpfWebServiceClient.ServiceReference1.GetFileContentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stableGeniuses.com/")]
    public partial class GetFileContentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file;
        
        public GetFileContentsRequestBody() {
        }
        
        public GetFileContentsRequestBody(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContentsResponse", Namespace="http://stableGeniuses.com/", Order=0)]
        public WpfWebServiceClient.ServiceReference1.GetFileContentsResponseBody Body;
        
        public GetFileContentsResponse() {
        }
        
        public GetFileContentsResponse(WpfWebServiceClient.ServiceReference1.GetFileContentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stableGeniuses.com/")]
    public partial class GetFileContentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfWebServiceClient.ServiceReference1.ArrayOfString GetFileContentsResult;
        
        public GetFileContentsResponseBody() {
        }
        
        public GetFileContentsResponseBody(WpfWebServiceClient.ServiceReference1.ArrayOfString GetFileContentsResult) {
            this.GetFileContentsResult = GetFileContentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WpfWebServiceClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WpfWebServiceClient.ServiceReference1.WebService1Soap>, WpfWebServiceClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfWebServiceClient.ServiceReference1.GetFileContentsResponse WpfWebServiceClient.ServiceReference1.WebService1Soap.GetFileContents(WpfWebServiceClient.ServiceReference1.GetFileContentsRequest request) {
            return base.Channel.GetFileContents(request);
        }
        
        public WpfWebServiceClient.ServiceReference1.ArrayOfString GetFileContents(string file) {
            WpfWebServiceClient.ServiceReference1.GetFileContentsRequest inValue = new WpfWebServiceClient.ServiceReference1.GetFileContentsRequest();
            inValue.Body = new WpfWebServiceClient.ServiceReference1.GetFileContentsRequestBody();
            inValue.Body.file = file;
            WpfWebServiceClient.ServiceReference1.GetFileContentsResponse retVal = ((WpfWebServiceClient.ServiceReference1.WebService1Soap)(this)).GetFileContents(inValue);
            return retVal.Body.GetFileContentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfWebServiceClient.ServiceReference1.GetFileContentsResponse> WpfWebServiceClient.ServiceReference1.WebService1Soap.GetFileContentsAsync(WpfWebServiceClient.ServiceReference1.GetFileContentsRequest request) {
            return base.Channel.GetFileContentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfWebServiceClient.ServiceReference1.GetFileContentsResponse> GetFileContentsAsync(string file) {
            WpfWebServiceClient.ServiceReference1.GetFileContentsRequest inValue = new WpfWebServiceClient.ServiceReference1.GetFileContentsRequest();
            inValue.Body = new WpfWebServiceClient.ServiceReference1.GetFileContentsRequestBody();
            inValue.Body.file = file;
            return ((WpfWebServiceClient.ServiceReference1.WebService1Soap)(this)).GetFileContentsAsync(inValue);
        }
    }
}
